# Generated by Django 4.2.28 on 2026-02-19 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo del documento (PDF o imagen)', upload_to='documentos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'tiff', 'bmp'])])),
                ('fecha_emision', models.DateField(blank=True, help_text='Fecha en que se emitió el documento', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del documento (usado para validación)', null=True)),
                ('estado', models.CharField(choices=[('verde', '🟢 Válido'), ('amarillo', '🟡 Requiere revisión'), ('rojo', '🔴 Inválido')], default='amarillo', help_text='Estado del semáforo de validación', max_length=10)),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto extraído mediante OCR (Fase 3)', null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de carga del documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
