# Generated by Django 4.2.28 on 2026-02-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='numero_documento_usuario',
            field=models.CharField(blank=True, help_text='Número de documento del usuario (ej. DNI, pasaporte) para validación', max_length=50, null=True),
        ),
    ]
