# Generated by Django 4.2.28 on 2026-03-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documental', '0002_documento_numero_documento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            # Nuevo modelo Convocatoria con campos básicos para gestionar convocatorias de carga de documentos.
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='confianza_ocr',
            field=models.IntegerField(default=0, help_text='Confianza OCR de 0 a 100'),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado_semaforo',
            field=models.CharField(choices=[('verde', '🟢 Válido'), ('amarillo', '🟡 Requiere revisión'), ('rojo', '🔴 Inválido')], default='amarillo', max_length=10),
        ),
        migrations.AddField(
            model_name='documento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_validacion',
            field=models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual')], default='automatica', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero_documento_usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True),
        ),

        #Modelo de perfil de usuario para asignar roles (admin, revisor, postulante) y gestionar permisos de acceso a funcionalidades.
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('revisor', 'Revisor'), ('postulante', 'Postulante')], default='postulante', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_documental', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        #Modelo de Postulante para almacenar información personal y de contacto de los usuarios que postulan a las convocatorias.
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(default='Cédula de Ciudadanía', max_length=50)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'ordering': ['-fecha_registro'],
            },
        ),
        #Modelo de DocumentoRequerido para definir los documentos que se requieren en cada convocatoria, con campos para nombre, descripción y obligatoriedad.
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('obligatorio', models.BooleanField(default=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_requeridos', to='documental.convocatoria')),
            ],
            options={
                'verbose_name': 'Documento Requerido',
                'verbose_name_plural': 'Documentos Requeridos',
                'unique_together': {('convocatoria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='convocatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documental.convocatoria'),
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_requerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to='documental.documentorequerido'),
        ),
        migrations.AddField(
            model_name='documento',
            name='postulante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documental.postulante'),
        ),
        #Modelo de Expediente para agrupar los documentos cargados por cada postulante en cada convocatoria, con estado del expediente (completo, incompleto, en proceso) y fechas de creación y actualización.
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('en_proceso', 'En Proceso')], default='en_proceso', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='documental.convocatoria')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='documental.postulante')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-creado_en'],
                'unique_together': {('postulante', 'convocatoria')},
            },
        ),
    ]
