# Generated by Django 4.2.28 on 2026-03-03 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0003_convocatoria_documento_confianza_ocr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='numero_documento',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{6,12}$', message='Formato de documento inválido')]),
        ),
    ]
