# Generated by Django 4.2.28 on 2026-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documental', '0004_alter_postulante_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
